In [1]:
from sklearn import linear_model
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.style.use('ggplot')

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame({
    'x1':[13, 18, 17, 20, 22, 21],
    'x2':[9, 7, 17, 11, 8, 10],
    'y':[20, 22, 30, 27, 35, 32]
})

In [4]:
data.index = ['A', 'B', 'C', 'D', 'E', 'F']; data

x1  x2   y
A  13   9  20
B  18   7  22
C  17  17  30
D  20  11  27
E  22   8  35
F  21  10  32

In [5]:
data['x1'] # 차량의 가격

A    13
B    18
C    17
D    20
E    22
F    21
Name: x1, dtype: int64

In [6]:
data['x1'].mean() # 차량의 가격 평균

18.5

In [7]:
data['x2'].mean() # 광고비의 평균

10.333333333333334

In [8]:
x1_star = data['x1'] - data['x1'].mean();  x1_star # 차량의 가격에서 평균을 뺀 값

A   -5.5
B   -0.5
C   -1.5
D    1.5
E    3.5
F    2.5
Name: x1, dtype: float64

In [9]:
x2_star = data['x2'] - data['x2'].mean(); x2_star # 공고비 가격에서 평균을 뺀 값

A   -1.333333
B   -3.333333
C    6.666667
D    0.666667
E   -2.333333
F   -0.333333
Name: x2, dtype: float64

In [10]:
y_star = data['y'] - data['y'].mean(); y_star # 판매액에서 평균을 뺀 값

A   -7.666667
B   -5.666667
C    2.333333
D   -0.666667
E    7.333333
F    4.333333
Name: y, dtype: float64

In [13]:
linear_regression = linear_model.LinearRegression()
linear_regression.fit(X = data[['x1', 'x2']], y = data['y'])
prediction = linear_regression.predict(data[['x1', 'x2']])
print('a value =', linear_regression.intercept_)
print('b value =', linear_regression.coef_)

a value = -7.359201773835938
b value = [1.5443459  0.62472284]


In [14]:
# y값 계산할 때 이런식으로 계산하면 됨
np.matmul(
    [[1,2]], # x1, x2 값을 넣음
    [[100], [200]] # b1과 b2값을 각각 넣음
) + 5 # a를 더함

array([[505]])

In [17]:
linear_regression.coef_

array([1.5443459 , 0.62472284])

In [18]:
linear_regression.coef_.tolist()

[1.5443458980044353, 0.6247228381374725]

In [20]:
np.matmul(
    [linear_regression.coef_.tolist()],
    [[20], [9]]
) + linear_regression.intercept_

array([[29.15022173]])

In [21]:
# 차 가격 30, 광고비 15일때 판매액 예측
np.matmul(
    [linear_regression.coef_.tolist()],
    [[30], [15]]
) + linear_regression.intercept_

array([[48.34201774]])

In [22]:
# 차 가격 20, 광고비 9
# 차 가격 30, 광고비 15
np.matmul(
    [linear_regression.coef_.tolist()],
    [[20, 30], [9, 15]]
) + linear_regression.intercept_

array([[29.15022173, 48.34201774]])

In [23]:
linear_regression.predict(
    X = [[20, 9], [30, 15]]
)

array([29.15022173, 48.34201774])

In [24]:
from sklearn import datasets
boston = datasets.load_boston()

In [25]:
boston

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [26]:
print(boston.keys())
print(boston.data.shape)
print(boston.feature_names)

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
(506, 13)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [27]:
X = pd.DataFrame(boston.data); X

0     1      2    3      4   ...   8      9     10      11    12
0    0.00632  18.0   2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1    0.02731   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2    0.02729   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03
3    0.03237   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63  2.94
4    0.06905   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90  5.33
..       ...   ...    ...  ...    ...  ...  ...    ...   ...     ...   ...
501  0.06263   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  391.99  9.67
502  0.04527   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  9.08
503  0.06076   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  5.64
504  0.10959   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  393.45  6.48
505  0.04741   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  7.88

[506 rows x 13 columns]

In [28]:
X.columns = boston.feature_names

In [29]:
X

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [30]:
X['price'] = boston.target; X

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  price
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1    0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2    0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3    0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4    0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67   22.4
502  0.04527   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08   20.6
503  0.06076   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64   23.9
504  0.10959   0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48   22.0
505  0.04741   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88   11.9

[506 rows x 14 columns]

In [31]:
y = X.pop('price'); y # X의 price 칸에 있는 값을 잘라내고 y에 저장함

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [32]:
X

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [33]:
X.shape

(506, 13)

In [34]:
linear_regression = linear_model.LinearRegression()
linear_regression.fit(X=X, y=y)
prediction = linear_regression.predict(X)
print('a value =', linear_regression.intercept_)
print('b value =', linear_regression.coef_)

a value = 36.459488385090125
b value = [-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
 -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
  3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
 -5.24758378e-01]


In [38]:
# 범죄율 0.02, 주거비중 0.1 상업지 비율 11, 찰스강 주변 1, 일산화질소농도 0.001, 집의방수 10, 1940년대 이전에 집비율 : 0.01,
# 직장거리 10, 고속도로 접근용이 1, 종부세 비율 273, 학생 교사 비율 30, 흑인비율 20, 급여가 낮은 직업 종사자 10
new = [0.02, 0.1, 11, 1, 0.001, 10, 0.01, 10, 1, 273, 30, 20, 10]; len(sample)

13

In [39]:
linear_regression.predict([new])

array([25.99501111])

In [40]:
residuals = y-prediction

In [42]:
residuals.describe()

count    5.060000e+02
mean     2.913787e-16
std      4.683822e+00
min     -1.559447e+01
25%     -2.729716e+00
50%     -5.180489e-01
75%      1.777051e+00
max      2.619927e+01
Name: price, dtype: float64

In [43]:
SSE = (residuals**2).sum()
SST = ((y-y.mean())**2).sum()
R_squared = 1 - (SSE/SST)
print('R_squared =', R_squared)  

R_squared = 0.7406426641094094


In [45]:
from sklearn.metrics import mean_squared_error
print('score =', linear_regression.score(X, y))
print('Mean Squared Error =', mean_squared_error(prediction, y))
print('RMSE =', mean_squared_error(prediction, y)**0.5)

score = 0.7406426641094095
Mean Squared Error = 21.894831181729202
RMSE = 4.679191295697281
