In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print("array3 array 형태:", array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3:2차원


In [9]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [10]:
# 더 범위로 변환됨
list1 = [1, 2, 'test']
array1 = np.array(list1)
print(array1, array1.dtype)

list1 = [1, 2, 3.0]
array1 = np.array(list1)
print(array1, array1.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [12]:
# ndarray 내 데이터 값의 타입 변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.8, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [14]:
# np.arange()를 통해서 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [16]:
# np.zeros()를 통해서 생성
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [20]:
# reshape()
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
# reshape을 사용할 때는 -1을 사용하면 그 부분은 알아서 만들어줌(크기를 고려해서) => 훨씬 편하게 코딩 가능
\array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d)
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [26]:
# numpy ndarray의 데이터 세트 선택하기(Indexing)

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [28]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [29]:
array1[0] = 9
array1[8] = 8
array1

array([9, 2, 3, 4, 5, 6, 7, 8, 8])

In [30]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가르키는 값:', array2d[0,0])
print('(row=0, col=1) index 가르키는 값:', array2d[0,1])
print('(row=1, col=0) index 가르키는 값:', array2d[1,0])
print('(row=2, col=2) index 가르키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가르키는 값: 1
(row=0, col=1) index 가르키는 값: 2
(row=1, col=0) index 가르키는 값: 4
(row=2, col=2) index 가르키는 값: 9


In [31]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [32]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [33]:
array2d = np.arange(start = 1, stop = 10).reshape(3,3)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [34]:
array2d[0]

array([1, 2, 3])

In [36]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[0,1], 0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [37]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [40]:
boolean_indexs = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexs]
print(array3)
indexs = np.array([5,6,7,8])
array4 = array1d[indexs]
print(array4)

[6 7 8 9]
[6 7 8 9]


In [42]:
org_array = np.array([3,1,9,5])
print(org_array)
sort_array1 = np.sort(org_array) # 정렬은 되지만 자체가 바뀌지 않음
print(sort_array1)
sort_array2 = org_array.sort() # org_array 자체가 정렬되어서 바뀜
print(sort_array2)

[3 1 9 5]
[1 3 5 9]
None


In [45]:
sort_array1_desc = np.sort(org_array)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [46]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [47]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices) # sort를 진행한 index순서

<class 'numpy.ndarray'>
[1 0 3 2]


In [48]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print(sort_indices)
print(name_array[sort_indices])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [50]:
# 선형대수 연산
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [51]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
