In [1]:
import pandas as pd

In [2]:
df01 = pd.DataFrame({
    'eng_rank':[1,4,2,9,9],
    'kor_rank':[3, 2, 7, 3, 10]
}); df01

eng_rank  kor_rank
0         1         3
1         4         2
2         2         7
3         9         3
4         9        10

In [3]:
# 편차
df01 - df01.mean()

eng_rank  kor_rank
0      -4.0      -2.0
1      -1.0      -3.0
2      -3.0       2.0
3       4.0      -2.0
4       4.0       5.0

In [4]:
((df01 - df01.mean())**2).sum() / (len(df01) - 1)

eng_rank    14.5
kor_rank    11.5
dtype: float64

In [5]:
((df01['kor_rank']-df01['kor_rank'].mean())**2).sum()/ (len(df01)-1)

11.5

In [6]:
## 영어 국어 공분산
((df01['eng_rank'] - df01['eng_rank'].mean()) * (df01['kor_rank'] - df01['kor_rank'].mean())).sum() / (len(df01) - 1)

4.25

In [7]:
df01.cov()

eng_rank  kor_rank
eng_rank     14.50      4.25
kor_rank      4.25     11.50

행열 연산

In [8]:
import numpy as np

In [9]:
A = np.array([
          [1, 2, 3],
          [4, 5, 6]
]); A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
B = np.array([
              [100, 500],
              [200, 600],
              [300, 700]
]); B

array([[100, 500],
       [200, 600],
       [300, 700]])

In [11]:
# 행렬의 곱
np.dot(A, B)

array([[1400, 3800],
       [3200, 9200]])

In [12]:
score = np.array([
          [1, 4, 2, 9, 9],
          [3, 2, 7, 3, 10]
]); score

array([[ 1,  4,  2,  9,  9],
       [ 3,  2,  7,  3, 10]])

In [13]:
# 행열방향 바꿈
score.T

array([[ 1,  3],
       [ 4,  2],
       [ 2,  7],
       [ 9,  3],
       [ 9, 10]])

In [14]:
# (score와 score행열방향바꿈 곱 - 평균 곱) / 데이터수 - 1 => 분산과 공분산이 나옴
np.dot(score-5, score.T-5) / 4

array([[14.5 ,  4.25],
       [ 4.25, 11.5 ]])

In [15]:
np.dot(score-score.mean(), score.T-score.mean())/ (len(score.T) - 1)

array([[14.5 ,  4.25],
       [ 4.25, 11.5 ]])

# 고유값 고유벡터
```
행렬
[4, 3]
[3, 5]
에 대한 고유값과 고유벡터
```


In [17]:
eigen_value = np.array([
                       [7, 0],
                       [0, 2]
]); eigen_value

array([[7, 0],
       [0, 2]])

In [18]:
eigen_vector = np.array([
                         [2, 3],
                         [-1, 1]
]); eigen_vector

array([[ 2,  3],
       [-1,  1]])

In [19]:
np.dot(eigen_value, eigen_vector)

array([[14, 21],
       [-2,  2]])

In [20]:
np.matmul(eigen_value, eigen_vector)

array([[14, 21],
       [-2,  2]])

In [21]:
np.matmul(eigen_vector, eigen_vector.T)

array([[13,  1],
       [ 1,  2]])

In [22]:
np.matmul(eigen_vector.T, eigen_vector)

array([[ 5,  5],
       [ 5, 10]])

In [28]:
inver = np.linalg.inv(eigen_vector); inver

array([[ 0.2, -0.6],
       [ 0.2,  0.4]])

In [27]:
np.matmul(eigen_vector, inver)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 5.55111512e-17,  1.00000000e+00]])

In [29]:
np.dot(eigen_vector, inver)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 5.55111512e-17,  1.00000000e+00]])

In [30]:
eigen_vector.T

array([[ 2, -1],
       [ 3,  1]])

# PCA 예제

In [48]:
import numpy as np
import pandas as pd

data = {
    'x1':[0.2, 0.45, 0.33, 0.54, 0.77],
    'x2' : [5.6, 5.87, 6.37, 7.9, 7.87],
    'x3' : [3.56, 2.4, 1.95, 1.32, 0.98],
    'y' : [100, 70, 60, 45, 30]
}

In [49]:
df = pd.DataFrame(data); df

x1    x2    x3    y
0  0.20  5.60  3.56  100
1  0.45  5.87  2.40   70
2  0.33  6.37  1.95   60
3  0.54  7.90  1.32   45
4  0.77  7.87  0.98   30

In [50]:
X = df[['x1', 'x2', 'x3']]

In [51]:
X.mean()

x1    0.458
x2    6.722
x3    2.042
dtype: float64

In [52]:
X.std()

x1    0.216264
x2    1.097073
x3    1.011197
dtype: float64

In [53]:
X = X - X.mean(); X

x1     x2     x3
0 -0.258 -1.122  1.518
1 -0.008 -0.852  0.358
2 -0.128 -0.352 -0.092
3  0.082  1.178 -0.722
4  0.312  1.148 -1.062

In [54]:
X.mean()

x1    0.000000e+00
x2    5.329071e-16
x3   -2.664535e-16
dtype: float64

In [55]:
X = X/X.std(); X

x1        x2        x3
0 -1.192988 -1.022721  1.501191
1 -0.036992 -0.776612  0.354036
2 -0.591870 -0.320854 -0.090981
3  0.379167  1.073766 -0.714005
4  1.442683  1.046420 -1.050240

In [56]:
print('평균')
print(X.mean())
print('표준 편차')
print(X.std())

평균
x1    0.000000e+00
x2    4.884981e-16
x3   -2.664535e-16
dtype: float64
표준 편차
x1    1.0
x2    1.0
x3    1.0
dtype: float64


In [57]:
# 줄 - 1만큼 나눔
X_cov = np.dot(X.T, X) / (5-1); X_cov

array([[ 1.        ,  0.83887873, -0.88401004],
       [ 0.83887873,  1.        , -0.91168074],
       [-0.88401004, -0.91168074,  1.        ]])

In [58]:
X.cov()

x1        x2        x3
x1  1.000000  0.838879 -0.884010
x2  0.838879  1.000000 -0.911681
x3 -0.884010 -0.911681  1.000000

In [59]:
eigen_value, eigen_vector = np.linalg.eig(X_cov)

print('고유값 :',eigen_value)
print('고유벡터 :', eigen_vector)

고유값 : [2.75671923 0.16413978 0.07914099]
고유벡터 : [[ 0.56993665  0.7754158   0.27185024]
 [ 0.57618187 -0.61301734  0.54057764]
 [-0.58582135  0.15145983  0.79616158]]


In [60]:
eigen_value[0]

2.7567192261431983

In [61]:
eigen_vector

array([[ 0.56993665,  0.7754158 ,  0.27185024],
       [ 0.57618187, -0.61301734,  0.54057764],
       [-0.58582135,  0.15145983,  0.79616158]])

In [62]:
eigen_vector.T[0]

array([ 0.56993665,  0.57618187, -0.58582135])

In [64]:
z1 = X.dot(eigen_vector.T[0]); z1

0   -2.148630
1   -0.675954
2   -0.468900
3    1.253065
4    2.040419
dtype: float64

In [65]:
z2 = X.dot(eigen_vector.T[1]); z2

0   -0.070746
1    0.501015
2   -0.276036
3   -0.472368
4    0.318136
dtype: float64

In [66]:
z3 = X.dot(eigen_vector.T[2]); z3

0    0.318016
1   -0.148005
2   -0.406782
3    0.115067
4    0.121704
dtype: float64

In [67]:
from sklearn.decomposition import PCA

In [68]:
pca = PCA(n_components = 3) # 3개의 z1, z2, z3를 계산한다는 의미

In [69]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [70]:
pca.singular_values_ # 고유값! eigen_value

array([3.32067416, 0.81028337, 0.56264017])

In [71]:
pca.components_.T # 1열 : e1, 2열 : e2, 3열 : e3

array([[-0.56993665,  0.7754158 , -0.27185024],
       [-0.57618187, -0.61301734, -0.54057764],
       [ 0.58582135,  0.15145983, -0.79616158]])

In [72]:
z = pca.fit_transform(X); z

array([[ 2.14863038, -0.07074582, -0.31801621],
       [ 0.6759543 ,  0.50101454,  0.1480055 ],
       [ 0.46889967, -0.27603645,  0.40678208],
       [-1.25306486, -0.47236838, -0.115067  ],
       [-2.04041949,  0.31813611, -0.12170436]])

In [73]:
eigen_value[0]

2.7567192261431983

In [74]:
sum(eigen_value)

2.9999999999999996

In [76]:
eigen_value[0] / sum(eigen_value) * 100 # z1이 전체에서 91%를 차지! 보통 77% 이상 차지하는 고유값 벡터가 있으면 해당 벡터로 회귀분석 실행

91.89064087143996

In [77]:
z1 = X.dot(eigen_vector.T[0]); z1

0   -2.148630
1   -0.675954
2   -0.468900
3    1.253065
4    2.040419
dtype: float64

In [78]:
from sklearn import linear_model

In [79]:
linear_regression = linear_model.LinearRegression()

In [80]:
linear_regression.fit(X = X, y = df['y'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [81]:
linear_regression.score(X = X, y = df['y']) # 전체 X를 다 이용하여 한 회귀분석은 R_square가 크긴하지만 overfitting

0.9978441052442628

In [82]:
linear_regression.fit(X=pd.DataFrame(z1), y = df['y'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [83]:
linear_regression.score(X=pd.DataFrame(z1), y = df['y']) # z1만을 이용해서 회귀분석. 비록 R_square가 X전체보다는 낮지만 95%이면 상당히 양호 그렇기 때문에 overfitting의 우려도 많이 사라짐

0.9592902066639692

# PCA를 이용한 보스턴 집값 예측

In [84]:
from sklearn.datasets import load_boston

In [85]:
boston_dataset = load_boston(); boston_dataset

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [86]:
boston_dataset.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [88]:
boston = pd.DataFrame(boston_dataset.data, columns = boston_dataset.feature_names); boston

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [89]:
y = boston_dataset.target; y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [90]:
boston.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

In [92]:
X = boston - boston.mean(); X

CRIM         ZN     INDUS  ...   PTRATIO          B     LSTAT
0   -3.607204   6.636364 -8.826779  ... -3.155534  40.225968 -7.673063
1   -3.586214 -11.363636 -4.066779  ... -0.655534  40.225968 -3.513063
2   -3.586234 -11.363636 -4.066779  ... -0.655534  36.155968 -8.623063
3   -3.581154 -11.363636 -8.956779  ...  0.244466  37.955968 -9.713063
4   -3.544474 -11.363636 -8.956779  ...  0.244466  40.225968 -7.323063
..        ...        ...       ...  ...       ...        ...       ...
501 -3.550894 -11.363636  0.793221  ...  2.544466  35.315968 -2.983063
502 -3.568254 -11.363636  0.793221  ...  2.544466  40.225968 -3.573063
503 -3.552764 -11.363636  0.793221  ...  2.544466  40.225968 -7.013063
504 -3.503934 -11.363636  0.793221  ...  2.544466  36.775968 -6.173063
505 -3.566114 -11.363636  0.793221  ...  2.544466  40.225968 -4.773063

[506 rows x 13 columns]

In [94]:
np.round(X.mean(), 3) # 거의 0이 나옴

CRIM      -0.0
ZN         0.0
INDUS     -0.0
CHAS      -0.0
NOX        0.0
RM        -0.0
AGE       -0.0
DIS        0.0
RAD        0.0
TAX        0.0
PTRATIO   -0.0
B          0.0
LSTAT     -0.0
dtype: float64

In [95]:
X.std()

CRIM         8.601545
ZN          23.322453
INDUS        6.860353
CHAS         0.253994
NOX          0.115878
RM           0.702617
AGE         28.148861
DIS          2.105710
RAD          8.707259
TAX        168.537116
PTRATIO      2.164946
B           91.294864
LSTAT        7.141062
dtype: float64

In [96]:
X = X / X.std(); X

CRIM        ZN     INDUS  ...   PTRATIO         B     LSTAT
0   -0.419367  0.284548 -1.286636  ... -1.457558  0.440616 -1.074499
1   -0.416927 -0.487240 -0.592794  ... -0.302794  0.440616 -0.491953
2   -0.416929 -0.487240 -0.592794  ... -0.302794  0.396035 -1.207532
3   -0.416338 -0.487240 -1.305586  ...  0.112920  0.415751 -1.360171
4   -0.412074 -0.487240 -1.305586  ...  0.112920  0.440616 -1.025487
..        ...       ...       ...  ...       ...       ...       ...
501 -0.412820 -0.487240  0.115624  ...  1.175303  0.386834 -0.417734
502 -0.414839 -0.487240  0.115624  ...  1.175303  0.440616 -0.500355
503 -0.413038 -0.487240  0.115624  ...  1.175303  0.440616 -0.982076
504 -0.407361 -0.487240  0.115624  ...  1.175303  0.402826 -0.864446
505 -0.414590 -0.487240  0.115624  ...  1.175303  0.440616 -0.668397

[506 rows x 13 columns]

In [97]:
X.std()

CRIM       1.0
ZN         1.0
INDUS      1.0
CHAS       1.0
NOX        1.0
RM         1.0
AGE        1.0
DIS        1.0
RAD        1.0
TAX        1.0
PTRATIO    1.0
B          1.0
LSTAT      1.0
dtype: float64

In [98]:
# 위의 과정을 StandardScaler가 만들어줌
from sklearn.preprocessing import StandardScaler
boston = pd.DataFrame(boston_dataset.data, columns = boston_dataset.feature_names); boston

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [99]:
# 데이터의 범위를 일정하게 만들어주는 객체 생성
scaler = StandardScaler()
# 각 칼럼의 평균 표준편차 계산
scaler.fit(boston)
# 데이터 - 평균 / 표준편차를 계산해서 각 칼럼의 데이터 범위를 일정하게 맞춰서 X_scaled에 대입
X = scaler.transform(boston)
X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [100]:
X = pd.DataFrame(X, columns = boston_dataset.feature_names); X

CRIM        ZN     INDUS  ...   PTRATIO         B     LSTAT
0   -0.419782  0.284830 -1.287909  ... -1.459000  0.441052 -1.075562
1   -0.417339 -0.487722 -0.593381  ... -0.303094  0.441052 -0.492439
2   -0.417342 -0.487722 -0.593381  ... -0.303094  0.396427 -1.208727
3   -0.416750 -0.487722 -1.306878  ...  0.113032  0.416163 -1.361517
4   -0.412482 -0.487722 -1.306878  ...  0.113032  0.441052 -1.026501
..        ...       ...       ...  ...       ...       ...       ...
501 -0.413229 -0.487722  0.115738  ...  1.176466  0.387217 -0.418147
502 -0.415249 -0.487722  0.115738  ...  1.176466  0.441052 -0.500850
503 -0.413447 -0.487722  0.115738  ...  1.176466  0.441052 -0.983048
504 -0.407764 -0.487722  0.115738  ...  1.176466  0.403225 -0.865302
505 -0.415000 -0.487722  0.115738  ...  1.176466  0.441052 -0.669058

[506 rows x 13 columns]

In [101]:
from sklearn.decomposition import PCA

pca = PCA(n_components=13)

In [102]:
# 종속변수 x1 ~ x13가 저장된 DataFrame X에서 z1 ~ z13까지 계산
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=13, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [105]:
print('고유값 :', pca.singular_values_)
print('고유값 벡터:\n', pca.components_.T)

고유값 : [55.6793095  26.93022859 25.07516773 20.83105866 20.55278239 18.23864114
 16.45874174 14.15716218 11.83779223 10.55653065  9.70171478  9.25566343
  5.66883461]
고유값 벡터:
 [[ 0.2509514  -0.31525237  0.24656649  0.06177071  0.08215692 -0.21965961
   0.77760721  0.15335048  0.26039028  0.01936913 -0.10964435  0.08676107
   0.0459523 ]
 [-0.25631454 -0.3233129   0.29585782  0.12871159  0.32061699 -0.3233881
  -0.27499628 -0.40268031  0.35813749  0.26752723  0.26275629 -0.07142528
  -0.08091897]
 [ 0.34667207  0.11249291 -0.01594592  0.01714571 -0.00781119 -0.0761379
  -0.33957645  0.17393172  0.64441615 -0.36353226 -0.30316943 -0.11319963
  -0.25107654]
 [ 0.00504243  0.45482914  0.28978082  0.81594136  0.08653094  0.16749014
   0.07413621 -0.02466215 -0.01372777 -0.00618184  0.01392667 -0.00398268
   0.03592171]
 [ 0.34285231  0.21911553  0.12096411 -0.12822614  0.13685356 -0.15298267
  -0.19963484  0.08012056 -0.01852201  0.23105645  0.11131888  0.80432257
   0.04363045]
 [-0.1892425

In [106]:
z = pca.transform(X); z 

array([[-2.09829747,  0.77311275,  0.34294273, ..., -0.03300036,
         0.01944023,  0.36597533],
       [-1.45725167,  0.59198521, -0.69519931, ..., -0.64080983,
        -0.12579741, -0.07071949],
       [-2.07459756,  0.5996394 ,  0.1671216 , ..., -0.48755672,
         0.13332653, -0.0140218 ],
       ...,
       [-0.31236047,  1.15524644, -0.40859759, ...,  0.11565634,
         0.28196407,  0.06247358],
       [-0.27051907,  1.04136158, -0.58545406, ...,  0.0870124 ,
         0.30170082,  0.05436991],
       [-0.12580322,  0.76197805, -1.294882  , ...,  0.18432101,
         0.23273318,  0.01970872]])

In [107]:
# 고유값 특징이 내림차순이라서 순서대로 77%를 넘는 지점까지 찾으면 됨!
sum(pca.singular_values_)

244.94362762279684

In [109]:
pca.singular_values_[0:7].sum() / pca.singular_values_.sum()

0.7502376425336473

In [110]:
pca.singular_values_[0:8].sum() / pca.singular_values_.sum() # 당첨!

0.8080352767158057

In [111]:
z.shape

(506, 13)

In [113]:
z.T.shape

(13, 506)

In [115]:
z = z.T[0:8]

In [116]:
z.shape

(8, 506)

In [117]:
z = z.T

In [118]:
z.shape

(506, 8)

In [119]:
zDF = pd.DataFrame(z); zDF

0         1         2  ...         5         6         7
0   -2.098297  0.773113  0.342943  ... -0.315338  0.318641  0.295832
1   -1.457252  0.591985 -0.695199  ...  0.264223  0.553861 -0.223670
2   -2.074598  0.599639  0.167122  ...  0.448095  0.484560  0.105166
3   -2.611504 -0.006871 -0.100284  ...  0.664649  0.622641  0.255941
4   -2.458185  0.097712 -0.075348  ...  0.617047  0.705086 -0.134524
..        ...       ...       ...  ...       ...       ...       ...
501 -0.314968  0.724285 -0.860896  ...  0.508064  0.199056 -0.249896
502 -0.110513  0.759308 -1.255979  ...  0.408208  0.191779 -0.146502
503 -0.312360  1.155246 -0.408598  ...  0.467947  0.294119 -0.638660
504 -0.270519  1.041362 -0.585454  ...  0.482259  0.271597 -0.579344
505 -0.125803  0.761978 -1.294882  ...  0.401474  0.175310 -0.133382

[506 rows x 8 columns]

In [120]:
from sklearn.linear_model import LinearRegression
# 선형회귀 객체 생성
linear_regression = LinearRegression()
# 선형회귀 실행
linear_regression.fit(zDF, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [121]:
linear_regression.score(X = zDF, y = y) # 13개 다썼을 때는 74%이기 때문에 성능차이가 거의 없음! 8개로 하는 것이 overfitting을 예방해줌

0.7055977712036576

# 실습

In [123]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston 

boston_dataset = load_boston()

In [124]:
boston = pd.DataFrame(boston_dataset.data, columns = boston_dataset.feature_names); boston

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [125]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(boston)
X = scaler.transform(boston); X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [126]:
X = pd.DataFrame(X, columns=boston_dataset.feature_names); X

CRIM        ZN     INDUS  ...   PTRATIO         B     LSTAT
0   -0.419782  0.284830 -1.287909  ... -1.459000  0.441052 -1.075562
1   -0.417339 -0.487722 -0.593381  ... -0.303094  0.441052 -0.492439
2   -0.417342 -0.487722 -0.593381  ... -0.303094  0.396427 -1.208727
3   -0.416750 -0.487722 -1.306878  ...  0.113032  0.416163 -1.361517
4   -0.412482 -0.487722 -1.306878  ...  0.113032  0.441052 -1.026501
..        ...       ...       ...  ...       ...       ...       ...
501 -0.413229 -0.487722  0.115738  ...  1.176466  0.387217 -0.418147
502 -0.415249 -0.487722  0.115738  ...  1.176466  0.441052 -0.500850
503 -0.413447 -0.487722  0.115738  ...  1.176466  0.441052 -0.983048
504 -0.407764 -0.487722  0.115738  ...  1.176466  0.403225 -0.865302
505 -0.415000 -0.487722  0.115738  ...  1.176466  0.441052 -0.669058

[506 rows x 13 columns]

In [127]:
from sklearn.decomposition import PCA
pca = PCA(n_components=13)

In [128]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=13, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [129]:
z = pca.transform(X)

In [130]:
pca.singular_values_[0:8].sum() / pca.singular_values_.sum()

0.8080352767158057

In [131]:
z.shape

(506, 13)

In [133]:
z[0:8].shape

(8, 13)

In [134]:
type(z)

numpy.ndarray

In [135]:
z[:,0:8].shape

(506, 8)

In [136]:
z = z[:, 0:8]

In [137]:
zDF = pd.DataFrame(z); zDF

0         1         2  ...         5         6         7
0   -2.098297  0.773113  0.342943  ... -0.315338  0.318641  0.295832
1   -1.457252  0.591985 -0.695199  ...  0.264223  0.553861 -0.223670
2   -2.074598  0.599639  0.167122  ...  0.448095  0.484560  0.105166
3   -2.611504 -0.006871 -0.100284  ...  0.664649  0.622641  0.255941
4   -2.458185  0.097712 -0.075348  ...  0.617047  0.705086 -0.134524
..        ...       ...       ...  ...       ...       ...       ...
501 -0.314968  0.724285 -0.860896  ...  0.508064  0.199056 -0.249896
502 -0.110513  0.759308 -1.255979  ...  0.408208  0.191779 -0.146502
503 -0.312360  1.155246 -0.408598  ...  0.467947  0.294119 -0.638660
504 -0.270519  1.041362 -0.585454  ...  0.482259  0.271597 -0.579344
505 -0.125803  0.761978 -1.294882  ...  0.401474  0.175310 -0.133382

[506 rows x 8 columns]

In [138]:
from sklearn.linear_model import LinearRegression

linear_regression = LinearRegression()
linear_regression.fit(zDF, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [140]:
linear_regression.score(X = zDF, y = y)

0.7055977712036576