In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [4]:
iris = load_iris()

In [5]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [6]:
x_train = iris.data[:-30] # -30은 뒤에서 30번째라는 의미
y_train = iris.target[:-30] 
x_test = iris.data[-30:]
y_test = iris.target[-30:]

In [8]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rfc = RandomForestClassifier(n_estimators=10) # default 값이 10개
rfc

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [15]:
rfc.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [16]:
prediction = rfc.predict(x_test); prediction

array([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
prediction == y_test

array([ True, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [19]:
rfc.score(x_test, y_test)

0.7333333333333333

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
confusion_matrix(y_test, prediction) # 행이 실제 값을 나타냄, 열이 예측값

array([[ 0,  0],
       [ 8, 22]])

In [23]:
confusion_matrix(prediction, y_test) # 행이 예측값, 열이 실제값

array([[ 0,  8],
       [ 0, 22]])

In [24]:
from sklearn.metrics import classification_report

In [26]:
print('Accuracy is :', accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

Accuracy is : 0.7333333333333333
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      0.73      0.85        30

    accuracy                           0.73        30
   macro avg       0.50      0.37      0.42        30
weighted avg       1.00      0.73      0.85        30



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2)
print(y_test)
print(Y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[1 1 2 1 2 0 2 2 0 2 0 2 2 1 1 0 1 2 0 1 0 0 2 1 0 2 1 0 0 1]


In [30]:
prediction_1 = rfc.predict(X_test)

print('Accuracy is :', accuracy_score(Y_test, prediction))
print(classification_report(Y_test, prediction_1))

Accuracy is : 0.36666666666666664
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [31]:
clf_2 = RandomForestClassifier(
    n_estimators = 200,
    max_features = 4,
    oob_score = True
)

In [32]:
clf_2.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [33]:
prediction_2 = clf_2.predict(X_test)

In [35]:
print('Accuracy is :', accuracy_score(Y_test, prediction_2))
print(classification_report(Y_test, prediction_2))

Accuracy is : 0.8666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.60      0.75        10
           2       0.71      1.00      0.83        10

    accuracy                           0.87        30
   macro avg       0.90      0.87      0.86        30
weighted avg       0.90      0.87      0.86        30



In [36]:
# 각 칸들을 200개 트리에서 사용한 비율
# 비율이 높은 칸은 Gini가 낮음(잘 나눠짐!)
# petal length (cm) : 57%
# petal width (cm) : 42%
clf_2.feature_importances_

array([0.0064427 , 0.00349783, 0.56961294, 0.42044653])

In [37]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [39]:
for feature, imp in zip(iris.feature_names, clf_2.feature_importances_):
  print('{} : {:.2f}%'.format(feature, imp * 100))

sepal length (cm) : 0.64%
sepal width (cm) : 0.35%
petal length (cm) : 56.96%
petal width (cm) : 42.04%


# 실습

In [40]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [42]:
iris = load_iris()

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rfc = RandomForestClassifier(n_estimators = 10)
rfc

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(y_test)

[1 0 1 1 1 0 1 0 2 1 2 2 1 1 2 1 2 0 2 1 1 1 1 1 1 2 2 0 2 2]


In [48]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [49]:
prediction = rfc.predict(X_test)

In [50]:
from sklearn.metrics import classification_report
print('Accuracy is :', accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

Accuracy is : 0.9
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      0.80      0.89        15
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.93      0.92        30
weighted avg       0.92      0.90      0.90        30



In [51]:
clf = RandomForestClassifier(n_estimators=200,
                             max_features = 4,
                             oob_score = True)
clf.fit(X_train, y_train)

prediction_1 = clf.predict(X_test)

print('Accuracy is :', accuracy_score(y_test, prediction_1))
print(classification_report(y_test, prediction_1))

Accuracy is : 0.8666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      0.73      0.85        15
           2       0.71      1.00      0.83        10

    accuracy                           0.87        30
   macro avg       0.90      0.91      0.89        30
weighted avg       0.90      0.87      0.87        30



In [52]:
for feature, imp in zip(iris.feature_names, clf.feature_importances_):
  print(feature, imp)

sepal length (cm) 0.0068155714498389424
sepal width (cm) 0.01034383772655861
petal length (cm) 0.5984408723437732
petal width (cm) 0.3843997184798293
